# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchentry',
            options={'verbose_name_plural': 'Search Entries'},
        ),
        migrations.AddField(
            model_name='searchentry',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchentry',
            name='last_search',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='searchentry',
            unique_together=set([('query', 'location')]),
        ),
    ]
